plugins {
    id 'java'
    id("com.diffplug.spotless") version "8.9.0"
}

ext.wpilibVersion = "2027.0.0-alpha-6"

repositories {
    mavenCentral()
    maven { url = 'https://frcmaven.wpi.edu/artifactory/release-2027' }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
var javaVersion = "25"

dependencies {
    implementation 'org.dyn4j:dyn4j:5.0.2'

    implementation "org.wpilib.ntcore:ntcore-java:$wpilibVersion"
    implementation "org.wpilib.wpilibj:wpilibj-java:$wpilibVersion"
    implementation "org.wpilib.wpiutil:wpiutil-java:$wpilibVersion"
    implementation "org.wpilib.wpimath:wpimath-java:$wpilibVersion"
    implementation "org.wpilib.wpiunits:wpiunits-java:$wpilibVersion"
    implementation "org.wpilib.hal:hal-java:$wpilibVersion"
}

javadoc {
    destinationDir = new File("$rootDir/../javadocs")

    exclude 'org/json/simple/**'
    options {
        links "https://docs.oracle.com/en/java/javase/$javaVersion/docs/api/", 'https://github.wpilib.org/allwpilib/docs/development/java/'
    }
}

spotless {
    java {
        target fileTree('.') {
            include '**/*.java'
            exclude '**/build/**', '**/build-*/**'
        }
        toggleOffOn()
        palantirJavaFormat('2.39.0').formatJavadoc(true)
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }

    groovyGradle {
        target fileTree('.') {
            include '**/*.gradle'
            exclude '**/build/**', '**/build-*/**'
        }
        greclipse()
        leadingTabsToSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
    }
    format 'misc', {
        target fileTree('.') {
            include '**/*.md', '**/.gitignore'
            exclude '**/build/**', '**/build-*/**'
        }
        trimTrailingWhitespace()
        leadingTabsToSpaces(4)
        endWithNewline()
    }
}

compileJava.dependsOn 'spotlessApply'

apply from: 'publish.gradle'

wrapper {
    gradleVersion '9.4.1'
}
